# Generated by Django 2.2.5 on 2019-09-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leavetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Postleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=30)),
                ('reason', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('leavetype', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leave.Leavetype')),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveAppUser',
        ),
    ]
